services:
  s-3dgs:
    container_name: s-3dgs
    image: ghcr.io/funnypocketbook/s-3dgs:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - /home/ydang/data/3dgs-data/git/s-3dgs/src:/workspace/s-3dgs
      - /home/ydang/data/3dgs-data/data:/workspace/data
      - /home/ydang/data/3dgs-data/output:/workspace/output
      - /home/ydang/data/3dgs-data/checkpoints/sam:/workspace/s-3dgs/encoders/sam_encoder/checkpoints
      - /home/ydang/data/3dgs-data/checkpoints/lseg:/workspace/lseg
      - /home/ydang/data/3dgs-data/checkpoints/clip:/workspace/clip
      - /home/ydang/data/3dgs-data/.vscode:/workspace/.vscode
      - /home/ydang/data/3dgs-data/vscode-server:$HOME/.vscode-server
      - /home/ydang/data/3dgs-data/workspace_action.sh:/workspace/workspace_action.sh:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:rw
    environment:
      - DISPLAY=$DISPLAY
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [compute,utility,graphics]

