services:
  s-3dgs:
    container_name: s-3dgs
    image: gitlab-int.nlr.nl:5050/dang/s-3dgs:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - /home/dang/git/s-3dgs/src:/workspace/s-3dgs
      - /home/dang/data:/workspace/data
      - /home/dang/output:/workspace/output
      - /home/dang/checkpoints/sam:/workspace/s-3dgs/encoders/sam_encoder/checkpoints
      - /home/dang/checkpoints/lseg:/workspace/lseg
      - /home/dang/checkpoints/clip:/workspace/clip
      - /home/dang/.vscode:/workspace/.vscode
      - /home/dang/vscode-server:$HOME/.vscode-server
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:rw
    environment:
      - DISPLAY=$DISPLAY
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [compute,utility,graphics]

