name: s-3dgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit-dev=11.7
  - python=3.8
  - pip=22.3.1
  - tqdm
  - pip:
    - plyfile 
    - tqdm
    - torch==1.13.1+cu117
    - torchvision==0.14.1+cu117
    - torchaudio==0.13.1
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn